[BankList]
BankList=Piano, Organ, Free Reed, Guitar And Bass, Strings, Brass, Woodwind, Synth, Drum, FX, Experimental

[Banks]
Brass=Brass, Slow_Brass, Trumpet
Drum=KickTecnoC1-TomG2, KickB1-TomG3, KickC2, SideStickC2s, ClapD2s, Claps, SnareD2, SnareE2, HitHatF2s, HitHatPedalG2s, HitHatOpenA2s, CowbellG3s, CowbellTecnoGs3, Crash, MaracasAs4, Tambourine
Experimental=Lost-Space-Voice, Tribal, Remember
FX=Birds, Noises, Ocean-WavesC3, Siren, Whip
Free%20Reed=Acordion, Harmonica
Guitar%20And%20Bass=Andaluza_Guitar, Andaluza_Guitar-Open, Steel_Guitar, Steel_Guitar-Open, Jazz_Guitar-Bass, Jazz_Guitar-Bass-Open, AmpliG, AmpliG-Open, DistorG, DistorG-Open, Overdrive, Overdrive-Open
Organ=Old_Organ, Modern_Organ
Piano=Egrand, Bringht_Egrand, HonkyTonk, MellowP, E_DX, RhodeX, WurlEZ, PianetE, Piano-Bass, ToyPi, ZlavinetE
Strings=Violin, Cello, Ensemble, Litany-StrWW
Synth=BassSynth, Lead_Bass, Lead_Pulse, Lead_Tau, Pad_PiAndChorus, FreeReedMix, ElectricHIT, PercuBrass, Static, kazO
Woodwind=NoiseFlute, Flute, Flutes, Bassoon, WoodWind

[PresetList]
PresetList=@Invalid()

[Presets]
Acordion=Acordion.synthv1
AmpliG=AmpliG.synthv1
AmpliG-Open=AmpliG-Open.synthv1
Andaluza_Guitar=Andaluza_Guitar.synthv1
Andaluza_Guitar-Open=Andaluza_Guitar-Open.synthv1
BassSynth=BassSynth.synthv1
Bassoon=Bassoon.synthv1
Birds=Birds.synthv1
Brass=Brass.synthv1
Bringht_Egrand=Bringht_Egrand.synthv1
Cello=Cello.synthv1
ClapD2s=ClapD2s.synthv1
Claps=Claps.synthv1
CowbellG3s=CowbellG3s.synthv1
CowbellTecnoGs3=CowbellTecnoGs3.synthv1
Crash=Crash.synthv1
DistorG=DistorG.synthv1
DistorG-Open=DistorG-Open.synthv1
E_DX=E_DX.synthv1
Egrand=Egrand.synthv1
ElectricHIT=ElectricHIT.synthv1
Ensemble=Ensemble.synthv1
Flute=Flute.synthv1
Flutes=Flutes.synthv1
FreeReedMix=FreeReedMix.synthv1
Harmonica=Harmonica.synthv1
HitHatF2s=HitHatF2s.synthv1
HitHatOpenA2s=HitHatOpenA2s.synthv1
HitHatPedalG2s=HitHatPedalG2s.synthv1
HonkyTonk=HonkyTonk.synthv1
Jazz_Guitar-Bass=Jazz_Guitar-Bass.synthv1
Jazz_Guitar-Bass-Open=Jazz_Guitar-Bass-Open.synthv1
KickB1-TomG3=KickB1-TomG3.synthv1
KickC2=KickC2.synthv1
KickTecnoC1-TomG2=KickTecnoC1-TomG2.synthv1
Lead_Bass=Lead_Bass.synthv1
Lead_Pulse=Lead_Pulse.synthv1
Lead_Tau=Lead_Tau.synthv1
Litany-StrWW=Litany-StrWW.synthv1
Lost-Space-Voice=Lost-Space-Voice.synthv1
MaracasAs4=MaracasAs4.synthv1
MellowP=MellowP.synthv1
Modern_Organ=Modern_Organ.synthv1
NoiseFlute=NoiseFlute.synthv1
Noises=Noises.synthv1
Ocean-WavesC3=Ocean-WavesC3.synthv1
Old_Organ=Old_Organ.synthv1
Overdrive=Overdrive.synthv1
Overdrive-Open=Overdrive-Open.synthv1
Pad_PiAndChorus=Pad_PiAndChorus.synthv1
PercuBrass=PercuBrass.synthv1
PianetE=PianetE.synthv1
Piano-Bass=Piano-Bass.synthv1
Remember=Remember.synthv1
RhodeX=RhodeX.synthv1
SideStickC2s=SideStickC2s.synthv1
Siren=Siren.synthv1
Slow_Brass=Slow_Brass.synthv1
SnareD2=SnareD2.synthv1
SnareE2=SnareE2.synthv1
Static=Static.synthv1
Steel_Guitar=Steel_Guitar.synthv1
Steel_Guitar-Open=Steel_Guitar-Open.synthv1
Tambourine=Tambourine.synthv1
ToyPi=ToyPi.synthv1
Tribal=Tribal.synthv1
Trumpet=Trumpet.synthv1
Violin=Violin.synthv1
Whip=Whip.synthv1
WoodWind=WoodWind.synthv1
WurlEZ=WurlEZ.synthv1
ZlavinetE=ZlavinetE.synthv1
kazO=kazO.synthv1
